///|
/// Controls overall biome size; higher => biomes change more frequently.
pub const BIOME_FREQ : Double = 0.0019

///|
pub const TEMP_FREQ : Double = BIOME_FREQ

///|
pub const HUMIDITY_FREQ : Double = BIOME_FREQ

///|
/// Controls continental drift scale; lower => larger landmass variation.
pub const CONTINENTAL_FREQ : Double = 0.0012

///|
pub const EROSION_FREQ : Double = 0.0021

///|
pub const WEIRDNESS_FREQ : Double = 0.0046

///|
pub const RIVER_FREQ : Double = 0.0032

///|
pub const RIDGE_FREQ_A : Double = 0.0068

///|
pub const RIDGE_FREQ_B : Double = 0.014

///|
const DEEP_OCEAN_CONTINENTAL_MAX : Double = -0.95

///|
const OCEAN_CONTINENTAL_MAX : Double = -0.86

///|
const BEACH_CONTINENTAL_MAX : Double = -0.60

///|
const DESERT_TEMP_THRESHOLD : Double = 0.30

///|
const DESERT_HUMID_THRESHOLD : Double = 0.02

///|
const FOREST_HUMID_THRESHOLD : Double = 0.0

///|
const MOUNTAIN_SCORE_THRESHOLD : Double = 0.85

///|
const WINDSWEPT_SCORE_THRESHOLD : Double = 0.46

///|
const DESERT_LAKES_EROSION_THRESHOLD : Double = 0.08

///|
const PLAINS_BASE_OFFSET : Double = 3.0

///|
const FOREST_BASE_OFFSET : Double = 4.0

///|
const MOUNTAIN_BASE_OFFSET : Double = 12.0

///|
const WINDSWEPT_BASE_OFFSET : Double = 8.0

///|
const DESERT_BASE_OFFSET : Double = 2.0

///|
const DESERT_LAKES_BASE_OFFSET : Double = 0.0

///|
const BEACH_BASE_OFFSET : Double = -2.0

///|
const RIVER_BASE_OFFSET : Double = -1.8

///|
const FROZEN_RIVER_BASE_OFFSET : Double = -1.8

///|
const OCEAN_BASE_OFFSET : Double = -6.0

///|
const DEEP_OCEAN_BASE_OFFSET : Double = -12.0

///|
const PLAINS_MOUNTAIN_AMP : Double = 14.0

///|
const FOREST_MOUNTAIN_AMP : Double = 15.0

///|
const MOUNTAIN_MOUNTAIN_AMP : Double = 58.0

///|
const WINDSWEPT_MOUNTAIN_AMP : Double = 34.0

///|
const DESERT_MOUNTAIN_AMP : Double = 11.0

///|
const DESERT_LAKES_MOUNTAIN_AMP : Double = 10.0

///|
const BEACH_MOUNTAIN_AMP : Double = 2.0

///|
const RIVER_MOUNTAIN_AMP : Double = 3.0

///|
const FROZEN_RIVER_MOUNTAIN_AMP : Double = 3.0

///|
const OCEAN_MOUNTAIN_AMP : Double = 1.4

///|
const DEEP_OCEAN_MOUNTAIN_AMP : Double = 1.4

///|
const PLAINS_MAX_HEIGHT : Int = 318

///|
const FOREST_MAX_HEIGHT : Int = 318

///|
const MOUNTAIN_MAX_HEIGHT : Int = 319

///|
const WINDSWEPT_MAX_HEIGHT : Int = 319

///|
const DESERT_MAX_HEIGHT : Int = 314

///|
const DESERT_LAKES_MAX_HEIGHT : Int = 306

///|
const BEACH_MAX_HEIGHT : Int = 72

///|
const RIVER_MAX_HEIGHT : Int = 72

///|
const FROZEN_RIVER_MAX_HEIGHT : Int = 72

///|
const OCEAN_MAX_HEIGHT : Int = 62

///|
const DEEP_OCEAN_MAX_HEIGHT : Int = 56
