///|
pub let redstone_torch_glow_min : Float = 6.5F / 16.0F

///|
pub let redstone_torch_glow_max : Float = 9.5F / 16.0F

///|
pub let redstone_torch_glow_y_min : Float = 7.5F / 16.0F

///|
pub let redstone_torch_glow_y_max : Float = 10.5F / 16.0F

///|
pub let redstone_torch_uv_up : (Float, Float, Float, Float) = @util.offset_uv_pixels(
  8, 5, 1, 1,
)

///|
pub let redstone_torch_uv_down : (Float, Float, Float, Float) = @util.offset_uv_pixels(
  7, 5, 1, 1,
)

///|
pub let redstone_torch_uv_north : (Float, Float, Float, Float) = @util.offset_uv_pixels(
  6, 6, 1, 1,
)

///|
pub let redstone_torch_uv_south : (Float, Float, Float, Float) = @util.offset_uv_pixels(
  9, 6, 1, 1,
)

///|
pub let redstone_torch_uv_west : (Float, Float, Float, Float) = @util.offset_uv_pixels(
  6, 7, 1, 1,
)

///|
pub let redstone_torch_uv_east : (Float, Float, Float, Float) = @util.offset_uv_pixels(
  9, 7, 1, 1,
)
