///|
/// Default water tint (rgb) and alpha.
/// 
/// Also see: https://zh.minecraft.wiki/w/%E6%B0%B4?variant=zh-cn (Color)
pub let default_water_tint : @util.Rgba = @util.rgba("#3f76e4")

///|
pub let swamp_water_tint : @util.Rgba = @util.rgba("#4c6559")

///|
pub let lukewarm_ocean_water_tint : @util.Rgba = @util.rgba("#45adf2")

///|
pub let warm_ocean_water_tint : @util.Rgba = @util.rgba("#43d5ee")

///|
pub let cold_ocean_water_tint : @util.Rgba = @util.rgba("#3d57d6")

///|
pub let frozen_water_tint : @util.Rgba = @util.rgba("#3938c9")

///|
pub let meadow_water_tint : @util.Rgba = @util.rgba("#0e4ecf")

///|
pub let mangrove_swamp_river_water_tint : @util.Rgba = @util.rgba("#3a7a6a")

///|
pub let cherry_grove_river_water_tint : @util.Rgba = @util.rgba("#5db7ef")

///|
pub let pale_garden_river_water_tint : @util.Rgba = @util.rgba("#76889d")

///|
pub let classic_water_tint : @util.Rgba = @util.rgba("#3341bd")
