///|
const GL_TRIANGLES : Int = 4

///|
const GL_STATIC_DRAW : Int = 35044

///|
const GL_FLOAT : Int = 5126

///|
const GL_UNSIGNED_INT : Int = 5125

///|
const GL_UNSIGNED_SHORT : Int = 5123

///|
const GL_RGBA : Int = 6408

///|
const GL_UNSIGNED_BYTE : Int = 5121

///|
const GL_TEXTURE_2D : Int = 3553

///|
const GL_ARRAY_BUFFER : Int = 34962

///|
const GL_ELEMENT_ARRAY_BUFFER : Int = 34963

///|
const GL_BLEND : Int = 3042

///|
const GL_CULL_FACE : Int = 2884

///|
const GL_SRC_ALPHA : Int = 770

///|
const GL_ONE_MINUS_SRC_ALPHA : Int = 771

///|
const GL_CCW : Int = 2305

///|
const GL_CW : Int = 2304

///|
const GL_VERTEX_SHADER : Int = 35633

///|
const GL_FRAGMENT_SHADER : Int = 35632

///|
const GL_COMPILE_STATUS : Int = 35713

///|
const GL_LINK_STATUS : Int = 35714

///|
const GL_TEXTURE_MAG_FILTER : Int = 10240

///|
const GL_TEXTURE_MIN_FILTER : Int = 10241

///|
const GL_TEXTURE_WRAP_S : Int = 10242

///|
const GL_TEXTURE_WRAP_T : Int = 10243
